### ISSUE TITLE
[ODT] - Workflow + Ajout de la convention de formation dans le contrat

### ISSUE THREAD

**Issue by evarisk-theo** [Evarisk/dolimeet#139]
- [x] Ajouter les champs standards dans les contacts des PR (Stagiaire, formateur, OPCO,Adresse de formation libre)
- [x] Ajouter un type pour la proposition, Projet, Contrat (Formation)
- [x] Remplir les notes publiques avec les informations demandées par les OPCO Dans les PDF en mode calculé Proposition et Contrat
- [x] Proposer 5 contrôles qualités par défaut (Importer les contrôles qualités sans les verrouiller (https://github.com/Evarisk/DigiQuali/issues/1820)
- [x] Ajouter les services standards "Convention de formation"
- [x] Ajouter les services standards "Livret d'accueil"
- [x] Ajouter les services standards "Réglement intérieur"

[convocation formation ](https://travail-emploi.gouv.fr/IMG/pdf/GUIDE_OF_V13.pdf)

**Comment by lmag** [comment]
https://www.evarisk.com/deroulement-de-votre-formation/

**Comment by lmag** [comment]
- [ ] Manque la Tache pour le suivi du temps du formateur liés au temps prévu de la formation


![image](https://github.com/Evarisk/dolimeet/assets/3288514/6ac535a0-9485-40b4-8f8e-b38f3346b4d5)

**Comment by nicolas-eoxia** [comment]
https://evarisk.biz/custom/dolimeet/view/session/session_card.php?id=169&object_type=meeting&save_lastsearch_values=1

**Comment by nicolas-eoxia** [comment]
CLient -> bouton créer formation choix formation .

partir du service -> choix tiers. 

Selecteur de service lié au tag formation

test avec un kit formations ??? 

Création projet 
Ajout service dédié

session pendant le contrat

**Comment by nicolas-eoxia** [comment]
Regénérer la note publique avec un button refresh
