### ISSUE TITLE
Mail de signature global

### ISSUE THREAD

**Issue by nicolas-eoxia** [Evarisk/dolimeet#278]
3dd87158dd2b6066a98ce0c266be2139c6599983

Mail d'envoi global -> foreach formateur / stagiare + lien

destinataire par défaut : tiers

box mail

**Comment by lmag** [comment]
mail template : 

Bonjour tiers

Veuillez .....
Stagiaire 1 : M. Nom, Prenom 
lien de signature
Stagiaire 2 : M. Nom, Prenom 
lien de signature
Stagiaire 3 : M. Nom, Prenom 
lien de signature

**Comment by nicolas-eoxia** [comment]
Bonjour, 

Suite à votre session de formation "INTITULE FORMATION" en date du JJ/MM/AAAA, veuillez trouver ci-dessous
les liens de signature des feuilles d'émargement des différents participants :


Nom Prénom
url

Nom Prénom
url

Nom Prénom
url


Nous vous remercions de bien vouloir leur transmettre.

Vous en souhaitant une excellente réception,

Cordialement
