### ISSUE TITLE
Contruction 3 mails globaux de relance d'enquete de statisfaction

### ISSUE THREAD

**Issue by lmag** [Evarisk/dolimeet#506]
Meme modèle que pour les signatures

- [x] Opco - Tous les contacts
- [x] Formation - Tous les users interne
- [x] Client - Tous les contacts du client

**Comment by nicolas-eoxia** [comment]
Modèle de mail 1 : Envoi du lien unitaire pour le contrôle
 Modèle de mail 2 : Envoi du mail avec tous les liens pour les questionnaires
 Envoi du mail pour l'opco
 Envoi du mail pour le client
