### ISSUE TITLE
Création des fiches de certifications

### ISSUE THREAD

**Issue by lmag** [Evarisk/dolimeet#597]
Test de reproduction @evarisk-francois 
1. Signature
2. Validation
3. Génération des certificats
4. message suivant

![image](https://github.com/user-attachments/assets/9f282a59-441c-443a-a5e2-517c03cf6a25)

**Comment by evarisk-francois** [comment]
Erreur sur demodoli, aucune erreur en local. Peut-être un problème avec un package.

**Comment by nicolas-eoxia** [comment]
Fix avec  #651 [Hook] add: rework generate document contract [9ef3cbe8ce5dda4a4fed4cda9c60c2a876272046]
