### ISSUE TITLE
Champs début de formation à supprimer ?

### ISSUE THREAD

**Issue by lmag** [Evarisk/dolimeet#633]
- [x] Suppresion des champs
- [ ] Ajout d'indicateurs sur la page principale de convention

![image](https://github.com/user-attachments/assets/b4665247-f7a0-41bb-a6b9-963b1a605e5b)

**Comment by nicolas-eoxia** [comment]
les champs dates ne servent pas car calculé par les sessions dans la note publique et l'OPCO est good si dans la note publique
