### ISSUE TITLE
Bug card tiers

### ISSUE THREAD

**Issue by EdgarLefevre** [Evarisk/dolimeet#644]
Bonjour, 

Lorsque j'active le module dolimeet, j'ai une page blanche à la place des cards tiers.

J'ai également d'autres modules Evarisk activés, cela peut-il poser problème ? 

![image](https://github.com/user-attachments/assets/8dd4ff95-53e0-4526-bd11-98680ae066ee)

Versions :
dolimeet : 1.4.0
saturne : 1.6.0
dolibarr : 19.0.2
php : 8.2.7

**Comment by lmag** [comment]
A priori certains modules ne sont pas à jour
PHP 8.2.7 ? Nous sommes en PHP 7.4.33 de notre côté
Avez-vous un fichier de log ?
